# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_geocoder.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('postal_code', models.IntegerField(null=True)),
            ],
            bases=(models.Model, django_geocoder.mixins.GeoMixin),
        ),
        migrations.CreateModel(
            name='InputAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(max_length=200)),
                ('cached_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocoding.CachedAddress')),
            ],
        ),
    ]
