# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedaddress',
            old_name='address',
            new_name='address_string',
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='address_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='place_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='state_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='street_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='street_name_post_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cachedaddress',
            name='zip_code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
